### ISSUE TITLE
Version number mismatch. Latest version is missing in the Arduino Library Manager.

### ISSUE THREAD

**Issue by UniK** [KLszTsu/fDigitsSegtPin#3]
The version number in the `library.properties` file (`version=1.1.2`) doesn't match the release number of this library (`1.1.3`) on the GitHub. As a result the Arduino Library Manager cannot see the latest version of this library (`1.1.3`), because the indexer skips it.

Please update the version properly.

Further info:
https://github.com/arduino/Arduino/wiki/Library-Manager-FAQ

**Comment by KLszTsu** [comment]
I'm really sorry for that. Thank you very much for reminding me.

**Comment by UniK** [comment]
Thanks, I'm closing it.
